Conditions:
  HasAlarmEmail:
    Fn::Not:
      - Fn::Equals:
          - ${param:alarmEmail, ''}
          - ""

Resources:
  MessagingAlarmEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlarmEmail
    Properties:
      Endpoint: ${param:alarmEmail, ''}
      Protocol: email
      TopicArn:
        Ref: MessagingAlarmTopic
